kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: n8n
spec:
  to:
    kind: Service
    name: n8n
    weight: 100
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect      