apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - postgres.yaml
  - keycloak-initial-admin.yaml
  - keycloak-db-secret.yaml
  - keycloak.yaml
  - keycloak-backstage-realm.yaml

namespace: rhbk
