{{- if eq .Values.elasticsearch.enabled true }}
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: elasticsearch-eck-operator-certified
  namespace: openshift-operators 
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  channel: {{ .Values.elasticsearch.channel }}
{{- if $.Values.elasticsearch.startingCSV }}
  startingCSV: {{ .Values.elasticsearch.startingCSV }}
{{- end }}
  installPlanApproval: Automatic
  name: elasticsearch-eck-operator-certified
  source: redhat-operators
  sourceNamespace: openshift-marketplace
---
apiVersion: v1
kind: Namespace
metadata:
  name: elasticsearch-eck-operator-certified
  annotations:
    argocd.argoproj.io/sync-wave: "1"
---
apiVersion: operators.coreos.com/v1alpha2
kind: OperatorGroup
metadata:
  name: elasticsearch-eck-operator-certified
  namespace: openshift-operators
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  targetNamespaces:
    - openshift-operators
{{- end }}