kind: ConfigMap
apiVersion: v1
metadata:
  name: rcsconfig
  namespace: developer-hub
  labels:
    rhdh.redhat.com/ext-config-sync: 'true'
  annotations:
    rhdh.redhat.com/backstage-name: developer-hub
data:
  rcsconfig.yaml: |
    llm_providers:
      # Start: Do not remove this block
      - name: dummy
        type: openai
        url: https://dummy.com
        models:
          - name: dummymodel
        # End: Do not remove this block
      - name: mistral-small
        type: mistral
        url: https://mistral-small-24b-w8a8-maas-apicast-production.apps.prod.rhoai.rh-aiservices-bu.com:443/v1
        models:
          - name: mistral-small-24b-w8a8        
    ols_config:
      user_data_collection:
        log_level: "DEBUG"
        feedback_disabled: false
        feedback_storage: "/tmp/feedback"
      reference_content:
        product_docs_index_path: "./vector_db/rhdh_product_docs/1.7"
        product_docs_index_id: rhdh-product-docs-1_7
        embeddings_model_path: "./embeddings_model"
      conversation_cache:
        type: memory
        memory:
          max_entries: 1000
      logging_config:
        app_log_level: info
        lib_log_level: warning
        uvicorn_log_level: info
        suppress_metrics_in_log: false
        suppress_auth_checks_warning_in_log: false
      authentication_config:
        module: "noop"
      default_provider: dummy
      default_model: dummymodel
      query_validation_method: disabled
    dev_config:
      enable_dev_ui: false
      disable_auth: false
      disable_tls: true
      enable_system_prompt_override: true
    user_data_collector_config:
      user_agent: "example-user-agent"
      ingress_url: "https://example.ingress.com/upload"
