kind: Secret
apiVersion: v1
metadata:
  name: secrets-rhdh
data:
  OLLAMA_TOKEN: c3NoLWVkMjU1MTkgQUFBQUMzTnphQzFsWkRJMU5URTVBQUFBSURFb2EyYmlwZnNhelRyeGxyR1NrMTBvYUE1cFRUN0EwbFBab3VwaTV6UVc=
  KEYCLOAK_CLIENT_ID: YmFja3N0YWdl
  KEYCLOAK_REALM: YmFja3N0YWdl
  CLIENT_SECRET: MjNkZjljYWE1ZThkYzg5YjRiYzk4MDA0ZTBjMjFkNzk4NDZiNmYyZQ==
  RHDH_BASE_URL: aHR0cHM6Ly9iYWNrc3RhZ2UtZGV2ZWxvcGVyLWh1Yi1kZXZlbG9wZXItaHViLmFwcHMucm9zYS5tNWNxOC1tYThrNC03czYuYWszcC5wMy5vcGVuc2hpZnRhcHBzLmNvbQ==
  ADMIN_TOKEN: OFB1eUxyOUEySHI1RXliN3VsU3Vsclg1
  KEYCLOAK_METADATA_URL: aHR0cHM6Ly9yaGJrLmFwcHMucm9zYS5tNWNxOC1tYThrNC03czYuYWszcC5wMy5vcGVuc2hpZnRhcHBzLmNvbS9yZWFsbXMvYmFja3N0YWdlLy53ZWxsLWtub3duL29wZW5pZC1jb25maWd1cmF0aW9u
  CLIENT_ID: T3YyM2xpUm5xZHFLZGM1RmhsZnQ=
  KEYCLOAK_BASE_URL: aHR0cHM6Ly9yaGJrLmFwcHMucm9zYS5tNWNxOC1tYThrNC03czYuYWszcC5wMy5vcGVuc2hpZnRhcHBzLmNvbQ==
  OLLAMA_URL: aHR0cDovL29sbGFtYToxMTQzNA==
  KEYCLOAK_CLIENT_SECRET: RmZ6akZBQXVRVUdqWkR0S1VFclR4OWZPYXFGN1JWNm0=
  RHDH_CALLBACK_URL: aHR0cHM6Ly9iYWNrc3RhZ2UtZGV2ZWxvcGVyLWh1Yi1kZXZlbG9wZXItaHViLmFwcHMucm9zYS5tNWNxOC1tYThrNC03czYuYWszcC5wMy5vcGVuc2hpZnRhcHBzLmNvbS9hcGkvYXV0aC9vaWRjL2hhbmRsZXIvZnJhbWU=
  BACKEND_SECRET: OFB1eUxyOUEySHI1RXliN3VsU3Vsclg1
type: Opaque
