channel: stable-4.17
version: 4.17.37
subscriptions:
  #- name: kiali-ossm
  #  namespace: openshift-operators
  #  channel: stable
  #  source: redhat-operators
  #- name: servicemeshoperator
  #  namespace: openshift-operators
  #  channel: stable
  #  source: redhat-operators
  - name: amq-streams
    namespace: openshift-operators
    channel: stable
    source: redhat-operators
  - name: amq-streams-console
    namespace: openshift-operators
    channel: alpha
    source: redhat-operators    
  - name: elasticsearch-eck-operator-certified
    namespace: openshift-operators
    channel: stable
    source: certified-operators
  - name: patch-operator
    namespace: patch-operator
    channel: alpha
    source: community-operators
  #- name: devspaces
  #  namespace: openshift-operators
  #  channel: stable
  #  source: redhat-operators
  #- name: 3scale-operator
  #  namespace: openshift-operators
  #  channel: threescale-2.15
  #  source: redhat-operators
  #- name: apicast-operator
  #  namespace: openshift-operators
  #  channel: threescale-2.15
  #  source: redhat-operators
  #- name: serverless-operator
  #  namespace: openshift-serverless
  #  channel: stable
  #  source: redhat-operators
  #- name: gitlab-operator-kubernetes
  #  namespace: gitlab-system
  #  channel: stable
  #  source: certified-operators
elasticsearch:
  namespace: elasticsearch-eck-operator-certified
  channel: stable
  startingCSV: elasticsearch-eck-operator-certified.v3.1.0
  enabled: true
rhdh:
  namespace: rhdh-operator
  channel: fast
  startingCSV: rhdh-operator.v1.7.0
  enabled: false
rhbk:
  namespace: rhbk-operator
  channel: stable-v26.2
  startingCSV: rhbk-operator.v26.2.7-opr.1
  enabled: false
gitlab:
  namespace: gitlab-system
  channel: stable
  startingCSV: gitlab-operator-kubernetes.v2.2.1
  source: community-operators
  instance:
    enabled: false
  enabled: false

acs:
  enabled: false
sealedsecrets:
  enabled: false
gitops:
  enabled: false
knative:
  enabled: false
kafka:
  enabled: false
  dedicatedNode: false
patchoperator:
  enabled: true
